# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2025, Foundries.io

# Persistência e diretórios
persistence true
persistence_location /mosquitto/data/

# Logs
log_dest file /mosquitto/log/mosquitto.log
log_type error
log_type warning
log_type notice
log_type information

# Segurança básica
allow_anonymous false
password_file /mosquitto/config/passwords

# Listener MQTT TCP
listener 1883
protocol mqtt

# Listener WebSocket (opcional)
listener 9001
protocol websockets

